<?php
/**
 * @var Magento\Framework\View\Element\Template $block
 * @var Magento\Framework\Escaper $escaper
 */
?>
<?php $posts = $block->getPosts(); ?>
<?php if ($posts): ?>
    <table>
        <tr>
            <th>title</th>
            <th>announce</th>
        </tr>
        <?php foreach ($posts as $post): ?>
            <?php /** @var VConnect\Blog\Model\Post $post */ ?>
            <tr>
                <td><?= $escaper->escapeHtml($post->getTitle()) ?></td>
                <td><?= $escaper->escapeHtml($post->getAnnounce()) ?></td>
                <td><a href="<?= $post->getUrlKey() ?>">Read post</a></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('Blog is empty')) ?></div>
    </div>
<?php endif; ?>
