<?php
/**
 * @var \VConnect\Blog\ViewModel\Posts $viewModel
 */
$viewModel = $block->getData('view_model');
?>

<table>
    <tr>
        <th>Id</th>
        <th>title</th>
        <th>content</th>
        <th>announce</th>
        <th>publish_date</th>
        <th>is_published</th>
        <th>created_at</th>
        <th>updated_at</th>
    </tr>

    <?php foreach ($viewModel->getPosts() as $post): ?>
        <?php /** @var VConnect\Blog\Model\Post $post */ ?>
        <tr>
            <td><?= $post->getId() ?></td>
            <td><?= $post->getTitle() ?></td>
            <td><?= $post->getContent() ?></td>
            <td><?= $post->getAnnounce() ?></td>
            <td><?= $post->getPublishDate() ?></td>
            <td><?= $post->getPostStatus() ?></td>
            <td><?= $post->getCreatedTime() ?></td>
            <td><?= $post->getUpdatedTime() ?></td>
        </tr>
    <?php endforeach; ?>
</table>
