<?php
/**
 * @var VConnect\Blog\Block\Posts $block
 * @var Magento\Framework\Escaper $escaper
 */
?>
<?php $posts = $block->getPosts(); ?>
<?php if ($posts): ?>
    <div class="products wrapper grid products-grid">
        <ol class="products list items product-items">
            <?php foreach ($posts as $post): ?>
                <?php /** @var VConnect\Blog\Model\Post $post */ ?>
                <li class="item product product-item">
                    <div class="product-item-info">
                        <div class="product details product-item-details">
                            <strong>
                                <a class="product-item-link" href="<?= $post->getUrlKey() ?>">
                                    <?= $escaper->escapeHtml($post->getTitle()) ?></a>
                            </strong>
                        </div>
                        <?= $escaper->escapeHtml($post->getAnnounce()) ?>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
<?php else: ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('Blog is empty')) ?></div>
    </div>
<?php endif; ?>
