<?php
/**
 * @var Magento\Framework\View\Element\Template $block
 * @var Magento\Framework\Escaper $escaper
 */
?>
<nav>
    <a href="/blog">Back</a>
</nav>

<?php $post = $block->getPost(); ?>
<?php if (isset($post)): ?>
    <table>
        <tr>
            <th>title</th>
            <th>content</th>
            <th>Created at</th>
            <th>Published at</th>
            <th>Updated at</th>
        </tr>

        <?php /** @var VConnect\Blog\Model\Post $post */ ?>
        <tr>
            <td><?= $escaper->escapeHtml($post->getTitle()) ?></td>
            <td><?= $post->getContent() ?></td>
            <td><?= $escaper->escapeHtml($post->getCreatedTime()) ?></td>
            <td><?= $escaper->escapeHtml($post->getPublishDate()) ?></td>
            <td><?= $escaper->escapeHtml($post->getUpdatedTime()) ?></td>
        </tr>

    </table>
<?php else: ?>
    <?= __('The post was deleted or unpublished') ?>
<?php endif; ?>
