<?php
/**
 * @var Magento\Framework\View\Element\Template $block
 * @var VConnect\Blog\ViewModel\Posts $viewModel
 * @var Magento\Framework\Escaper $escaper
 */
$viewModel = $block->getData('view_model');
?>

<nav>
    <a href="/blog">Back</a>
</nav>

<table>
    <tr>
        <th>title</th>
        <th>content</th>
        <th>Created at</th>
        <th>Published at</th>
        <th>Updated at</th>
    </tr>
    <?php foreach ($viewModel->getPosts() as $post): ?>
        <?php /** @var VConnect\Blog\Model\Post $post */ ?>
        <tr>
            <td><?= $escaper->escapeHtml($post->getTitle()) ?></td>
            <td><?= $post->getContent() ?></td>
            <td><?= $escaper->escapeHtml($post->getCreatedTime()) ?></td>
            <td><?= $escaper->escapeHtml($post->getPublishDate()) ?></td>
            <td><?= $escaper->escapeHtml($post->getUpdatedTime()) ?></td>
        </tr>
    <?php endforeach; ?>
</table>
